start_cycle:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: energy_ledger

end_cycle:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: energy_ledger
